prometheus:
  serviceMonitor:
    enabled: true

database:
  enabled: true # Set to true for self-hosted, false for managed RDS
  image: "postgres:15"
  username: "vikunja"
  secretName: "vikunja-db-secret"

frontend:
  image: "vikunja/frontend:0.22.1"
  host: vikunja.local
  replicaCount: 1
  hpa:
    minReplicas: 2
    maxReplicas: 5
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

backend:
  image: "vikunja/api:0.22.1"
  host: vikunja.local
  replicaCount: 1
  hpa:
    minReplicas: 2
    maxReplicas: 5
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

ingress:
  enabled: true
  host: vikunja.local
