apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja-backend
  labels:
    app: vikunja-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: vikunja-backend
  template:
    metadata:
      labels:
        app: vikunja-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}"
          ports:
            - containerPort: 3456
          env:
            - name: VIKUNJA_METRICS_ENABLED
              value: "true"
            - name: VIKUNJA_SERVICE_FRONTENDURL
              value: "http://{{ include "vikunja.frontend.host" . }}"
            - name: VIKUNJA_CORS_ENABLE
              value: "true"
            - name: VIKUNJA_CORS_ORIGINS
              value: "*"
            - name: VIKUNJA_DATABASE_HOST
              value: "{{ include "vikunja.database.host" . }}"
            - name: VIKUNJA_DATABASE_TYPE
              value: "{{ include "vikunja.database.type" . }}"
            - name: VIKUNJA_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: database-user
            - name: VIKUNJA_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: database-password
            {{- range .Values.backend.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            requests:
              cpu: {{ .Values.backend.resources.requests.cpu }}
              memory: {{ .Values.backend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.backend.resources.limits.cpu }}
              memory: {{ .Values.backend.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: /api/v1/info
              port: 3456
          readinessProbe:
            httpGet:
              path: /api/v1/info
              port: 3456

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vikunja-backend-hpa
  labels:
    app: vikunja-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vikunja-backend
  minReplicas: {{ .Values.backend.hpa.minReplicas | default 2 }}
  maxReplicas: {{ .Values.backend.hpa.maxReplicas | default 5 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: vikunja-backend
  annotations:
    {{- if (default false .Values.prometheus.serviceMonitor.enabled) }}
    prometheus.io/scrape: "true"
    {{- end }}
  labels:
    app: vikunja-backend
spec:
  selector:
    app: vikunja-backend
  ports:
    - protocol: TCP
      port: 3456
      targetPort: 3456
      name: http
  type: ClusterIP  # Ensures it's only accessible within the cluster
---
{{- if (default false .Values.prometheus.serviceMonitor.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vikunja-backend-monitor
  labels:
    app: vikunja-backend
spec:
  selector:
    matchLabels:
      app: vikunja-backend
  endpoints:
    - port: "http"
      path: /api/v1/metrics
      interval: 60s
{{- end }}
