apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja-frontend
  labels:
    app: vikunja-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: vikunja-frontend
  template:
    metadata:
      labels:
        app: vikunja-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}"
          ports:
            - containerPort: 80
          env:
            - name: VIKUNJA_API_URL
              value: "http://{{ include "vikunja.backend.host" . }}/api/v1"
            {{- range .Values.frontend.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu }}
              memory: {{ .Values.frontend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu }}
              memory: {{ .Values.frontend.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app: vikunja-frontend
data:
  VITE_API_URL: "http://vikunja-backend"  # Internal ClusterIP access
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vikunja-frontend-hpa
  labels:
    app: vikunja-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vikunja-frontend
  minReplicas: {{ .Values.frontend.hpa.minReplicas | default 2 }}
  maxReplicas: {{ .Values.frontend.hpa.maxReplicas | default 5 }}
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: v1
kind: Service
metadata:
  name: vikunja-frontend
  labels:
    app: vikunja-frontend
  annotations:
    {{- if (default false .Values.prometheus.serviceMonitor.enabled) }}
    prometheus.io/scrape: "true"
    {{- end }}
spec:
  selector:
    app: vikunja-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
{{- if (default false .Values.prometheus.serviceMonitor.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vikunja-frontend-monitor
  labels:
    app: vikunja-frontend
spec:
  selector:
    matchLabels:
      app: vikunja-frontend
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
{{- end }}

