{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vikunja
  annotations:
    nginx.ingress.kubernetes.io/proxy-pass-headers: "Authorization"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "http-cookie"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/load-balance: "least_conn"  # Load balancing strategy ; least connections
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "5s"  # Connection timeout; Reduces connection establishment time.
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"  # Number of buffers
    nginx.ingress.kubernetes.io/keep-alive: "timeout=60s"  # Keep-alive for persistent connections; This allows persistent TCP connections, which can significantly reduce latency for repeat requests.
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: vikunja-backend
                port:
                  number: 3456
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vikunja-frontend
                port:
                  number: 80
{{- end }}
